FROM mesosphere/mesos:0.20.1
MAINTAINER Lolo Fernanez<lolo.fernandez@sirca.org.au>

RUN apt-get update
RUN apt-get install -y curl python python-pip python-dev build-essential
RUN pip2 install jupyter
