# -*- mode: ruby -*-
# vim: ft=ruby


# ---- Configuration variables ----

GUI               = false # Enable/Disable GUI
RAM               = 256  # Default memory size in MB

# Network configuration
DOMAIN            = ".local"

HOSTS = {
   "controller" => [RAM, GUI, "knservis/controller"],
   "elk" => [RAM, GUI, "knservis/elk"],
   "node1" => [RAM, GUI, "knservis/node"],
   "node2" => [RAM, GUI, "knservis/node"],
}

# ---- Vagrant configuration ----

Vagrant.configure(2) do |config|
  HOSTS.each do | (name, cfg) |
    ram, gui, box = cfg

    config.vm.define name do |machine|
      machine.vm.box     = box
      machine.vm.provider "virtualbox" do |vbox|
        vbox.gui    = gui
        vbox.memory = ram
      end

      machine.vm.hostname = name + DOMAIN
      machine.vm.network :private_network, type: 'dhcp'
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.limit = 'all'
    ansible.playbook = "ansible/vagrant.yml"
    ansible.groups = {
      "nodes" => HOSTS.select{ |k,v| k.include? "node"}.keys
    }
  end
end